network:
  kwargs:
    nonlinear: "PReLU"

train_dataset:
  name: 'Naive'
  kwargs:
    path: "../results/"
    len: 1000

PCA:
  kwargs: {}

optimizer:
  name: 'SGD'
  kwargs: 
    lr: 0.01
    momentum: 0
    dampening: 0
    weight_decay: 0
    nesterov: false

lr_scheduler:
  name: 'StepLR'
  kwargs:
    step_size: 1273
    gamma: 0.25

loss:
  name: 'MSE'
  kwargs: {}


loader:
  shuffle: True
  batch_size: 16
  num_workers: 0
  drop_last: false


checkpoint: null
use_gpu: True
epoch: 10
# evaluator:
#   name: 'Default'
#   kwargs: {}

valid: "../results/generated/10_generated.png"